SELECT  CAST(id as INT) as movie_id, 
        CAST(index as INT) as movie_index, 
        CAST("Release_Date" as DATE) as release_date,
        "IMDB_URL" as imdb_url,
        "Name" as name,
        CAST(CAST("War" as INT) as BOOLEAN) as war,
        CAST(CAST("Crime" as INT) as BOOLEAN) as crime,
        CAST(CAST("Drama" as INT) as BOOLEAN) as drama,
        CAST(CAST("Action" as INT) as BOOLEAN) as action,
        CAST(CAST("Comedy" as INT) as BOOLEAN) as comedy,
        CAST(CAST("Horror" as INT) as BOOLEAN) as horror,
        CAST(CAST("Sci_Fi" as INT) as BOOLEAN) as sci_Fi,
        CAST(CAST("Fantasy" as INT) as BOOLEAN) as fantasy,
        CAST(CAST("Musical" as INT) as BOOLEAN) as musical,
        CAST(CAST("Mystery" as INT) as BOOLEAN) as mystery,
        CAST(CAST("Romance" as INT) as BOOLEAN) as romance,
        CAST(CAST("Western" as INT) as BOOLEAN) as western,
        CAST(CAST("unknown" as INT) as BOOLEAN) as unknown,
        CAST(CAST("Thriller" as INT) as BOOLEAN) as thriller,
        CAST(CAST("Adventure" as INT) as BOOLEAN) as adventure,
        CAST(CAST("Animation" as INT) as BOOLEAN) as animation,
        CAST(CAST("Film_Noir" as INT) as BOOLEAN) as film_noir,
        CAST(CAST("Children_s" as INT) as BOOLEAN) as children_s,
        CAST(CAST("Documentary" as INT) as BOOLEAN) as documentary
FROM {{ source('recommmender_system_raw', 'movies') }}

