dbt_mlops_profile:
  outputs:
    dev:
      dbname: "{{ env_var('WAREHOUSE_DB') }}"
      host: "{{ env_var('PGHOST') }}"
      pass: "{{ env_var('AIRBYTE_WAREHOUSE_PASSWORD') }}"
      port: "{{ env_var('PGPORT') | as_number }}"
      schema: "{{ env_var('WAREHOUSE_TARGET_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('AIRBYTE_WAREHOUSE_USER') }}"
  target: dev
