------Airbyte-dbt Objects
CREATE USER :"AIRBYTE_WAREHOUSE_USER" WITH ENCRYPTED PASSWORD :'AIRBYTE_WAREHOUSE_PASSWORD';
ALTER USER :"AIRBYTE_WAREHOUSE_USER" CREATEDB;
SET ROLE :"AIRBYTE_WAREHOUSE_USER";
CREATE DATABASE :WAREHOUSE_DB;
------MLFlow Objects
SET ROLE "postgres";
CREATE USER :"MLFLOW_POSTGRES_USER" WITH ENCRYPTED PASSWORD :'MLFLOW_POSTGRES_PASSWORD';
ALTER USER :"MLFLOW_POSTGRES_USER" CREATEDB;
SET ROLE :"MLFLOW_POSTGRES_USER";
CREATE DATABASE :MLFLOW_POSTGRES_DB;